base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.loginPage, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.registerPage, name = "register"),

    path('student-home', views.studentHome, name='student-home'),
    path('student-course-lookup', views.studentCourseLookup, name='student-course-lookup'),
    path('student-request-tutor', views.studentTutorSearch, name='student-request-tutor'),
    path('student-submit-request', views.studentSubmitRequest, name='student-submit-request'),
    path('student-notification', views.studentNotification, name='student-notification'),

    path('tutor-home', views.tutorHome, name = 'tutor-home'),
    path('tutor-course-lookup', views.tutorCourseLookup, name='tutor-course-lookup'),
    path('tutor-post-rate', views.tutorPostRate, name='post-rate'),
    path('tutor-view-rate', views.tutorViewRate, name='view-rate'),
    path('tutor-view-courses', views.tutorViewCourses, name='tutor-view-courses'),
    path('tutor-notification', views.tutorNotification, name='tutor-notification'),
    path('tutor-post-timeframe', views.tutorPostTimeFrame, name='tutor-post-timeframe'),
    path('tutor-view-timeframes', views.tutorViewTimeFrames, name='tutor-view-timeframes'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),

]

base/models.py
from django.conf import settings
from django.db import models
from django.forms import DateInput
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Student(models.Model):
    full_name = models.CharField(max_length = 80)
    username = models.CharField(max_length = 80)

    student_all_tutors = models.ManyToManyField('Tutor', through = 'Notification')

    def __str__(self):
        return self.username
    
class Tutor(models.Model):
    username = models.CharField(max_length = 80)
    hourly_rate = models.CharField(max_length = 40)
    #Represents the list of courses for a particular tutor (courses the tutor has posted)
    tutor_all_courses = models.ManyToManyField('Course', through = 'CourseTutored')
    tutor_all_students = models.ManyToManyField('Student', through = 'Notification')

    def __str__(self):
        return self.username
    
class Course(models.Model):
    department = models.CharField(max_length=8) #Example: 'APMA'
    number = models.CharField(max_length = 8, default = "0000") #Example: '3080'
    name = models.CharField(max_length=200) #Example: 'Linear Algebra'
    #Represents the list of tutors for a particular course (allows students to view tutors for that course)
    course_all_tutors = models.ManyToManyField('Tutor', through = 'CourseTutored')

    def __str__(self):
        return self.department + " " + self.number + " " + self.name

#Django "Through" tables that establishes direct connection between Tutors and Courses
class CourseTutored(models.Model):
    tutor = models.ForeignKey(Tutor, on_delete = models.CASCADE)
    course = models.ForeignKey(Course, on_delete = models.CASCADE)
    def __str__(self):
        return str(self.course) + " tutored by " + str(self.tutor.username)


class Notification(models.Model):
    info = models.CharField(max_length=200, default="0")
    course = models.CharField(max_length=200)
    student = models.ForeignKey(Student, on_delete = models.CASCADE)
    tutor = models.ForeignKey(Tutor, on_delete = models.CASCADE)

    def __str__(self):
        return self.course + " " + self.student.username + " " + self.tutor.username
    
class TimeFrame(models.Model):
    start_time = models.TimeField()
    end_time = models.TimeField()
    tutor = models.ForeignKey(Tutor, on_delete = models.CASCADE)

    def __str__(self):
        return self.tutor.username + ":  " + str(self.start_time) + " to " + str(self.end_time)

base/forms.py
from django import forms

class TutorLookupForm(forms.Form): #finds the class then finds the tutors associated with that class
    department = forms.CharField(max_length=8) #Example: 'APMA'
    number = forms.CharField(max_length=8) #Example: '3080'
    name = forms.CharField(max_length=200)

class TutorPostCourseForm(forms.Form):
    department = forms.CharField(max_length=8) #Example: 'APMA'
    number = forms.CharField(max_length=8) #Example: '3080'
    name = forms.CharField(max_length=200)

class TutorPostRateForm(forms.Form):
    rate = forms.CharField(max_length = 8)

class TutorRemoveCourseForm(forms.Form):
    department = forms.CharField(max_length=8) #Example: 'APMA'
    number = forms.CharField(max_length=8) #Example: '3080'
    name = forms.CharField(max_length=200)

class StudentRequestTutorForm(forms.Form):
    tutor = forms.CharField(max_length=40)

class TutorNotificationForm(forms.Form):
    info = forms.CharField(max_length=1)
    student = forms.CharField(max_length=40)
    course = forms.CharField(max_length=80)

class StudentNotificationForm(forms.Form):
    info = forms.CharField(max_length=1)
    tutor = forms.CharField(max_length=40)
    course = forms.CharField(max_length=80)

class TimeInput(forms.TimeInput):
    input_type = 'time'

class StudentTimeFrameForm(forms.Form):
    start_time = forms.TimeField(widget=TimeInput)
    end_time = forms.TimeField(widget=TimeInput)

class TutorPostTimeFrameForm(forms.Form):
    start_time = forms.TimeField(widget=TimeInput)
    end_time = forms.TimeField(widget=TimeInput)

base/views.py
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect
from django.contrib.auth import login as logins, logout as logouts

from .models import Student, Tutor, Course, CourseTutored, Notification, TimeFrame

from .forms import TutorPostCourseForm, TutorLookupForm, TutorPostRateForm, TutorRemoveCourseForm, StudentRequestTutorForm, TutorNotificationForm, StudentNotificationForm, TutorPostTimeFrameForm, StudentTimeFrameForm
from django.views.generic import ListView
from django.db.models import Q

from .decorators import allowed_users


def index(request):
    return render(request, 'base/index.html')


def is_student(user):
    return user.groups.filter(name='student').exists()


def is_tutor(user):
    return user.groups.filter(name='tutor').exists()


# -------------------------------------------------------

def loginPage(request):
    if request.user.is_active:
        if not is_student(request.user) and not is_tutor(
                request.user):  # if the logged in user is not a tutor or student, make them register to be one
            return registerPage(request)
        if is_student(request.user):
            return studentHome(request)
        if is_tutor(request.user):
            return tutorHome(request)
    return render(request, 'base/general_login.html')  # Puts person at the page where they can be recorded as a "user"


def logout(request):
    if request.method == "POST":
        logouts(request)
        return render(request, 'base/index.html')
    return render(request, 'base/general_logout.html')


def registerPage(request):
    if (request.GET.get('student')):  # add student group attribute
        group = Group.objects.get(name='student')
        request.user.groups.add(group)
        group = Group.objects.get(name='tutor')
        request.user.groups.remove(group)
        return register_student(request)
    elif (request.GET.get('tutor')):  # add tutor group attribute
        group = Group.objects.get(name='tutor')
        request.user.groups.add(group)
        group = Group.objects.get(name='student')
        request.user.groups.remove(group)
        return register_tutor(request)
    else:
        return render(request, 'base/register.html')


# -------------------------------------------------

# Creates student object if needed
def register_student(request):
    user_name = request.user.username
    s = Student(username=user_name)
    if not Student.objects.filter(username=user_name).exists():
        s.save()
    return render(request, 'base/student_home.html')


# Creates tutor object if needed
def register_tutor(request):
    user_name = request.user.username
    t = Tutor(username=user_name)
    if not Tutor.objects.filter(username=user_name).exists():
        t.save()
    return render(request, 'base/tutor_home.html')


# ------------------------------------------------

# Only lets users with "student" group access page
@allowed_users(allowed_roles=['student'])
def studentHome(request):
    return render(request, 'base/student_home.html')

@allowed_users(allowed_roles=['student'])
def studentCourseLookup(request):
    if request.method == "GET":
        query = request.GET.get("q")
        object_list = Course.objects.filter(
            Q(department=query) | Q(number = query) | Q(name = query)
        )
        return render(request, 'base/student_search_course.html', {'object_list': object_list})
    if request.method == "POST":
        form = TutorLookupForm(request.POST)
        if form.is_valid():
            department = str(form.cleaned_data['department'])  # first find the right course
            number = str(form.cleaned_data['number'])
            name = str(form.cleaned_data['name'])
            if Course.objects.filter(department=department, number=number, name=name).exists():  # Ensures that an incorrect course is not posted
                c = Course.objects.get(department=department, number=number, name=name)

                request.session['department'] = department
                request.session['number'] = number
                request.session['name'] = name
                request.session['tutors'] = list(c.course_all_tutors.values()) # store tutor search in user session
                return redirect('base:student-request-tutor')
    form = TutorLookupForm()
    return render(request, 'base/student_search_course.html', {'form': form})

@allowed_users(allowed_roles=['student'])
def studentTutorSearch(request):
    course = Course.objects.get(department=request.session['department'], number=request.session['number'], name=request.session['name'])
    if request.method == "POST":
        form = StudentRequestTutorForm(request.POST)
        if form.is_valid():
            tutor = str(form.cleaned_data['tutor'])
            request.session['tutor'] = tutor
            return redirect('base:student-submit-request')
    form = StudentRequestTutorForm(request.POST)

    print((request.session['tutors']))

    return render(request, 'base/student_tutors_available.html', {'form': form, 'course': course, 'tutors': request.session['tutors']})

@allowed_users(allowed_roles=['student'])
def studentSubmitRequest(request):
    course = Course.objects.get(department=request.session['department'], number=request.session['number'], name=request.session['name'])
    student = Student.objects.get(username=request.user.username)
    tutor = Tutor.objects.get(username=request.session['tutor'])
    info = "0"
    tutor_timeframes = TimeFrame.objects.filter(tutor = tutor)

    if request.method == "POST":
        request_form = StudentRequestTutorForm(request.POST)
        time_form = StudentTimeFrameForm(request.POST)

        if time_form.is_valid():
            print("time form valid")
            student_chosen_start_time = (time_form.cleaned_data['start_time'])
            student_chosen_end_time = (time_form.cleaned_data['end_time'])
            #User submits time
        
            #Need to go through all time frames to ensure this is a valid time
            for timeframe in tutor_timeframes:
                this_endTime = timeframe.end_time
                this_startTime = timeframe.start_time
                if student_chosen_start_time >= this_startTime and student_chosen_end_time <= this_endTime and student_chosen_start_time < student_chosen_end_time:
                    if not Notification.objects.filter(info=info, course=course, student=student,tutor=tutor).exists():
                        Notification(info=info, course=course, student=student,tutor=tutor).save()
                        return redirect('base:student-notification')

    request_form = StudentRequestTutorForm(request.POST)
    time_form = StudentTimeFrameForm(request.POST)


    return render(request, 'base/student_submit_request.html', {'form': request_form, 'time_form': time_form, 'course': course, 'student': student, 'tutor': tutor , 'tutor_timeframes': tutor_timeframes})

@allowed_users(allowed_roles=['student'])
def studentNotification(request):
    student = Student.objects.get(username=request.user.username)
    notifications = Notification.objects.filter(student=student)

    if request.method == "POST":
        form = StudentNotificationForm(request.POST)
        if form.is_valid():
            info = str(form.cleaned_data['info'])
            tutor = Tutor.objects.get(username=str(form.cleaned_data['tutor']))
            course = str(form.cleaned_data['course'])
            Notification.objects.get(info=info, course=course, student=student,tutor=tutor).delete()
            return redirect('base:student-notification')
    form = StudentNotificationForm()
    return render(request, 'base/student_notification.html', {'form': form, 'notifications': notifications})

# -----------------------------------------------

# Only lets users with "tutor" group access page
@allowed_users(allowed_roles=['tutor'])
def tutorHome(request):
    return render(request, 'base/tutor_home.html')

@allowed_users(allowed_roles=['tutor'])
def tutorCourseLookup(request):
    if request.method == "GET":
        query = request.GET.get("q")
        object_list = Course.objects.filter(
            Q(department=query) | Q(number = query) | Q(name = query)
        )
        return render(request, 'base/tutor_search_course.html', {'object_list': object_list})
    if request.method == "POST":
        form = TutorPostCourseForm(request.POST)
        if form.is_valid():
            t = Tutor.objects.get(username=request.user.username)  # find the right tutor model
            department = str(form.cleaned_data['department'])
            number = str(form.cleaned_data['number'])
            name = str(form.cleaned_data['name'])
            if Course.objects.filter(department=department, number=number, name=name).exists():  # Ensures that an incorrect course is not posted
                c = Course.objects.get(department=department, number=number, name=name)
                if not CourseTutored.objects.filter(tutor=t, course=c).exists():  # Ensures that we don't add duplicate Course-Tutor relationship
                    CourseTutored(tutor=t, course=c).save()  # adds course to tutor object and adds tutor to course object
                return redirect('base:tutor-view-courses')
    form = TutorPostCourseForm()
    return render(request, 'base/tutor_search_course.html', {'form': form})

# View courses function
@allowed_users(allowed_roles=['tutor'])
def tutorViewCourses(request):
    t = Tutor.objects.get(username=request.user.username)
    if request.method == "POST":
        form = TutorRemoveCourseForm(request.POST)
        if form.is_valid():
            t = Tutor.objects.get(username=request.user.username)  # find the right tutor model

base/templates/base/general_logout.html
{% block nav %}{% include 'base/general_navbar.html' %}{% endblock nav %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'base/styles.css' %}">

<div class="d-flex flex-column align-items-center">
    <div style="height: 270px;"></div>
    <h1 style="color:aliceblue">Do you wish to log out?</h1>
    <div class="d-flex flex-column align-items-center">
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-outline-light" type="submit" value="Logout">
                Confirm Logout
            </button>
        </form>
    </div>
</div>
</html>

base/templates/base/index.html
{% block nav %}{% include 'base/general_navbar.html' %}{% endblock nav %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'base/styles.css' %}">
<title>Tutor Me</title>

<body class="joemama">
<div class="container">
    <h1> <span class="auto-type"></span></h1>
</div>

{#Source for animation: https://www.youtube.com/watch?v=qEcXe51-ZTw&ab_channel=EasyTutorials#}
<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
<script>
    var typed = new Typed(".auto-type",{
        strings: ["Tutor Me", "Learning", "Success"],
        typeSpeed: 150,
        backSpeed:150,
        loop: true
    })
</script>

<style>
    .joemama {
        margin: 0;
        padding: 0;
        font-family: 'Poppins', sans-serif;
    }
    .container{
        width: 100%;
        color: #fff;
        align-items: center;
        justify-content: center;
        transform: translateY(190%) translateX(37%);
    }

    .container h1{
        font-size: 80px;
        font-weight: 600;
    }
    span{
        color: #F8F0FB;
    }
</style>
</body>

base/templates/base/student_navbar.html
{% load static %} 
<link rel="icon" href="http://example.com/favicon.png">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Students</title>
    <link rel="icon" type="image/x-icon" href={% static "base/images/uva.png" %}>
</head>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #2a2a3b">
    <a class="navbar-brand">
        </a><a href="/student-home"><img src={% static "base/images/uva.png" %} width="50" height="50"></a>

    <div class="collapse navbar-collapse justify-content-center" id="navbarCenteredExample">
        <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item"><a style="color: #F8F0FB" class="nav-link" href="/student-notification">View Notifications</a></li>
            <li class="nav-item"><a style="color: #F8F0FB" class="nav-link" href="/student-course-lookup">Course Search</a></li>
        </ul>
    </div>
    <a class="nav-link" href="/logout">
        <button class="btn btn-outline-light" type="button">Log Out</button>
      </a>

</nav>

base/templates/base/student_notification.html
{% block nav %}{% include 'base/student_navbar.html' %}{% endblock nav %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'base/styles.css' %}">

<!-- PAGE TITLE -->
<div style="height: 50px;"></div>
<div class="d-flex flex-column align-items-center">
  <h1 style="color:aliceblue;">Your Notifications:</h1>
</div>
<div style="height: 30px;"></div>


<!-- LIST OF NOTIFICATIONS -->
<div class="d-flex flex-column align-items-center">
    <div style="height: 10px;"></div>
    {% for notification in notifications %} 
    <div class="text-center col-md-12">
        <ol>
            {% if notification.info == "0" %} 
                <p style="color:aliceblue;">You have requested {{notification.tutor}} as a tutor for {{notification.course}}</p>
            {% elif notification.info == "1" %} 

                <div class="d-flex flex-row justify-content-center">
                    <form>
                        <button class="btn btn-success">{{notification.tutor}} has accepted your tutoring request for {{notification.course}}</button>
                    </form>
                    <div style="width: 10px;"></div>
                    <form method="post">
                    {% csrf_token %}
                        <input type="hidden" name="info" value='1'>
                        <input type="hidden" name="tutor" value='{{notification.tutor}}'>
                        <input type="hidden" name="course" value='{{notification.course}}'>
                        <button type="submit" class="btn btn-outline-warning" >clear</button>
                    </form>
                </div>

            {% elif notification.info == "2" %} 

                <div class="d-flex flex-row justify-content-center">
                    <form>
                        <button class="btn btn-outline-danger">{{notification.tutor}} has rejected your tutoring request for {{notification.course}}</button>
                    </form>
                    <div style="width: 10px;"></div>
                    <form method="post">
                    {% csrf_token %}
                        <input type="hidden" name="info" value='2'>
                        <input type="hidden" name="tutor" value='{{notification.tutor}}'>
                        <input type="hidden" name="course" value='{{notification.course}}'>
                        <button type="submit" class="btn btn-outline-warning" >clear</button>
                    </form>
                </div>

            {% endif %} 
        </ol>
    </div>
    {% endfor %}

</div>

base/templates/base/student_registration.html
{% block nav %}{% include 'base/navbar.html' %}{% endblock nav %}

{% load static %}


<body>    
    <center> <h1 style="color:aliceblue;"> Student Registration </h1> </center>
    <form>  
        <div class="container">   
            <label style="color:aliceblue;">First Name : </label>
            <input type="text" placeholder="Enter Full Name" name="full_name" required>  
            <br>
            <button type="submit">Submit</button>   
        </div>   
    </form>     
</body>     

base/templates/base/student_search_course.html
{% block nav %}{% include 'base/student_navbar.html' %}{% endblock nav %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'base/styles.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- PAGE TITLE -->
<div style="height: 70px;"></div>
<div class="d-flex flex-column align-items-center">
  <h1 style="color:aliceblue;">Search Course for Tutor</h1>
</div>
<div style="height: 20px;"></div>


<!-- SEARCH BAR -->
<div class="row">
  <div class="col-lg-8 mx-auto">
    <div class="p-5">
      
      <form action="{% url 'base:student-course-lookup' %}" method="get">
        <div class="p-1 rounded rounded-pill shadow-sm">
          <div class="input-group">
            <input name="q" type="text" placeholder="Search for a course...?" aria-describedby="button-addon1" class="form-control border-0 bg-light">
            <div class="input-group-append" >
              <button id="button-addon1" type="submit" class="btn btn-link text-primary"><i class="fa fa-search" style="color:aliceblue;"></i></button>
            </div>
          </div>
        </div>
      </form>
    
      </div>
  </div>
</div>


<!-- LIST OF COURSES -->
<div class="d-flex flex-column align-items-center">
  <div style="height: 10px;"></div>
  <ul style"list-style-type: none;">
    {% for course in object_list %}
      <div class="text-center mt-2 col-md-12">
        <ol>
          <div class="d-flex flex-row justify-content-center">
              <form method="post">
                {% csrf_token %}
                <input type="hidden" name="department" value='{{ course.department }}'>
                <input type="hidden" name="number" value='{{ course.number }}'>
                <input type="hidden" name="name" value='{{ course.name }}'>
                <button type="submit" class="btn btn-outline-light" >{{course.department}} {{course.number}} {{course.name}}</button>
              </form>

              <div style="width: 10px;"></div>

              <form method="post">
                {% csrf_token %}
                <input type="hidden" name="department" value='{{ course.department }}'>
                <input type="hidden" name="number" value='{{ course.number }}'>
                <input type="hidden" name="name" value='{{ course.name }}'>
                <button type="submit" class="btn btn-outline-light" ><i class="fa fa-search"></i></button>
            </form>
          </div>
        </ol>
      </div>
    {% endfor %}
  </ul>
</div>


base/templates/base/tutorSearch.html
{#{% block nav %}{% include 'base/navbar.html' %}{% endblock nav %}#}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'base/styles.css' %}">

<div class="d-flex flex-column align-items-center">
    <div style="height: 10px;"></div>
    <h1>Tutors</h1>
    {% for i in response %}
        <strong>{{ name}}  </strong>
        <a> {{ hourly_rate }}</a>
        <a> {{ time_frames }}</a>
        <a> {{ classes }}</a>
    {% endfor %}
    <div style="height: 10px;"></div>
</div>

<div class="d-flex justify-content-center"></div>

base/templates/base/tutor_home.html
{% block nav %}{% include 'base/tutor_navbar.html' %}{% endblock nav %}

{% load static %}
{#Source: https://www.youtube.com/watch?v=rc50owRPdUI&ab_channel=EasyTutorials#}
<link rel="stylesheet" type="text/css" href="{% static 'base/styles.css' %}">
<div class="container1">
    <div class="text-box">
        <p>Welcome, Tutor</p>
        <h1>{{ user }}</h1>
    </div>
</div>

<style>
    .text-box {
        color: #F8F0FB;
        position: absolute;
        bottom: 8%;
    }

    .text-box p {
        font-size: 50px;
        font-weight: 600;
    }

    .text-box h1 {
        text-transform: uppercase;

        font-size: 190px;
        line-height: 160px;
        margin-left: -10px;
        color: transparent;
        -webkit-text-stroke: 1px white;
        background: url(/static/base/images/stripes.png);
        -webkit-background-clip: text;
        background-position: 0 0;
        animation: back 20s linear infinite;
    }

    @keyframes back {
        100% {
            background-position: 2000px 0;
        }
    }

    .text-box a {
        color: #F8F0FB;
        text-decoration: none;
        padding: 10px 20px;
        margin-right: 20px;
        border: 2px solid #F8F0FB;
    }
</style>

base/templates/base/tutor_navbar.html
{% load static %}
<link rel="icon" href="http://example.com/favicon.png">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Tutors</title>
    <link rel="icon" type="image/x-icon" href={% static "base/images/uva.png" %}>
</head>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #2a2a3b">
    <a class="navbar-brand">
        </a><a href="/tutor-home"><img src={% static "base/images/uva.png" %} width="50" height="50"></a>

    <div class="collapse navbar-collapse justify-content-center" id="navbarCenteredExample">
        <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item"><a style="color: #F8F0FB" class="nav-link" href="/tutor-notification">Notifications</a></li>
            <li class="nav-item"><a style="color: #F8F0FB" class="nav-link" href="/tutor-view-courses">My Courses</a></li>
            <li class="nav-item"><a style="color: #F8F0FB" class="nav-link" href="/tutor-view-rate">Hourly Rate</a></li>
            <li class="nav-item"><a style="color: #F8F0FB" class="nav-link" href="/tutor-view-timeframes">Time Frames</a></li>
        </ul>
    </div>
    <a class="nav-link" href="/logout">
        <button class="btn btn-outline-light" type="button">Log Out</button>
      </a>
</nav>

base/templates/base/tutor_search_course.html
{% block nav %}{% include 'base/tutor_navbar.html' %}{% endblock nav %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'base/styles.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- PAGE TITLE -->
<div style="height: 70px;"></div>
<div class="d-flex flex-column align-items-center">
  <h1 style="color:aliceblue;">Add Course to Profile</h1>
</div>
<div style="height: 20px;"></div>


<!-- SEARCH BAR -->
<div class="row">
  <div class="col-lg-8 mx-auto">
    <div class="p-5">
      
      <form action="{% url 'base:tutor-course-lookup' %}" method="get">
        <div class="p-1 rounded rounded-pill shadow-sm">
          <div class="input-group">
            <input name="q" type="text" placeholder="Search for a course...?" aria-describedby="button-addon1" class="form-control border-0 bg-light">
            <div class="input-group-append" >
              <button id="button-addon1" type="submit" class="btn btn-link text-primary"><i class="fa fa-search" style="color:aliceblue;"></i></button>
            </div>
          </div>
        </div>
      </form>
  
      </div>
  </div>
</div>


<!-- LIST OF COURSES -->
<div class="d-flex flex-column align-items-center">
  <div style="height: 10px;"></div>
  <ul style"list-style-type: none;">
    {% for course in object_list %}

      <div class="text-center mt-2 col-md-12">
        <ol>
          <div class="d-flex flex-row justify-content-center">
              <form method="post">
                {% csrf_token %}
                <input type="hidden" name="department" value='{{ course.department }}'>
                <input type="hidden" name="number" value='{{ course.number }}'>
                <input type="hidden" name="name" value='{{ course.name }}'>
                <button type="submit" class="btn btn-outline-light" >{{course.department}} {{course.number}} {{course.name}}</button>
              </form>

              <div style="width: 10px;"></div>

              <form method="post">
                {% csrf_token %}
                <input type="hidden" name="department" value='{{ course.department }}'>
                <input type="hidden" name="number" value='{{ course.number }}'>
                <input type="hidden" name="name" value='{{ course.name }}'>
                <button type="submit" class="btn btn-success" >add</button>
            </form>
          </div>
        </ol>
      </div>
    {% endfor %}
  </ul>
</div>
